import React from "react"


class CreateClass extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			classId: "",
			className: "",
			classDescription: ""
		}
	}


	handleChange = (event) => {
		console.log(event.target.value);
	}

	handleSubmit = (event) => {
		event.preventDefault();

	}

	render() {
		return (
			<div className="container">
				<form className="white" onSubmit={this.handleSubmit}>
					<h5 className="grey-text text-darken-3">Add A Class</h5>

					<div className="input-field">
						<label htmlFor="classId">Class ID (This will be generated by default)</label>
						<input type="text" id="classId" onChange={this.handleChange}/>
					</div>

					<div className="input-field">
						<label htmlFor="className">Class Name</label>
						<input type="text" id="className" onChange={this.handleChange}/>
					</div>

					<div className="input-field">
						<label htmlFor="classDescription">Class Description</label>
						<input type="text" id="className" onChange={this.handleChange}/>
					</div>

					<div className="input-field">
						<a className="waves-effect waves-light btn" href="/">Add Class</a>
					</div>

				</form>
			</div>
		)

	}

}

export default CreateClass