GET http://localhost:3000/users
###

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "name":"Shubham",
    "password": "pass"
}
###
GET https://google.com/
###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "name":"Shubham",
    "password": "pass"
}
###